![Header Image](../assets/header_image.png "Header Image")

# Tâche facultative 2 : Python, NumPy et vectorisation

Cette tâche vous offre une brève introduction à certains des calculs scientifiques utilisés dans ce cours. Nous utiliserons la populaire bibliothèque NumPy qui est utilisée pour de nombreuses applications de calcul scientifique.

Dans cette tâche facultative, vous apprendrez sur NumPy et d'autres compétences en Python recommandées à connaître pour les prochaines tâches. Ce notebook est recommandé aux étudiants qui n'ont aucune expérience en NumPy. Vous apprendrez sur :

- Vecteurs
- Matrices
- Opérations sur les matrices
- Opérations sur les vecteurs
- Indexation
- Accès aux éléments
- Vectorisation

Commençons par importer numpy. Exécutez la cellule ci-dessous.


In [1]:
import numpy as np
import time

Vous pouvez voir que nous avons importé Numpy en tant que `np`. C'est l'abréviation de `numpy` et nous pouvons maintenant accéder à toutes les fonctions numpy avec `np` :


In [2]:
np.sum([1, 2, 3])

6

## Références

Nous ne pouvons fournir ici qu'une introduction limitée à NumPy, car cette bibliothèque est assez vaste et possède de nombreuses fonctionnalités. Consultez le lien ci-dessous si vous souhaitez en savoir plus sur cette bibliothèque :
- Documentation de NumPy : [NumPy.org](https://NumPy.org/doc/stable/)


## Python et NumPy

Python est l'un des langages de programmation que nous utiliserons dans ce MOOC. Il est devenu très populaire parmi les data scientists et les ingénieurs en apprentissage automatique, car il prend en charge de nombreuses bibliothèques et outils différents tels que les cahiers Jupyter. De plus, la syntaxe est assez facile à comprendre, mais prend en charge la programmation orientée objet complète, ainsi que les opérations mathématiques de base. NumPy est une bibliothèque Python qui donne à Python la puissance fondamentale pour le calcul scientifique. Il ajoute la prise en charge de plus de types de données numériques, de vecteurs, de matrices et d'opérations de matrice. De plus, le cœur de NumPy est basé sur un code C bien optimisé qui permet des calculs rapides et efficaces.


### Vecteurs, matrices et tenseurs

Avant d'entrer dans les détails, commençons par rappeler comment les noms de certains objets mathématiques sont souvent utilisés en informatique.

- **Vecteur** est un tableau ou un tuple avec une seule dimension (il n'y a pas de différence entre les vecteurs ligne et les vecteurs colonne).
- **Matrice** fait référence à un tableau avec deux dimensions.
- **Tenseur** pour des tableaux tridimensionnels ou de dimensions supérieures.


# Vecteurs

Un vecteur $x$ fait référence à une collection unidimensionnelle d'éléments, où tous les éléments ont le même type de données. La "longueur" d'un vecteur fait souvent référence au nombre de ses éléments. $\text{len}(x) = n$ pour l'exemple ci-dessous. En utilisant Python et NumPy, nous désignons souvent la longueur le long d'une *dimension*. Les vecteurs sont représentés par des tableaux ou des tuples 1D. Chaque élément dans un tableau peut être accédé avec un index. En algèbre linéaire, les éléments d'un vecteur sont souvent indexés de $1$ à $n$, où $i=1$ désigne le premier élément $x_1$ et $n$ le dernier élément $x_n$. Cependant, dans les langages de programmation, on commence généralement à compter à partir de 0. Ainsi, le $0^{ème}$ élément $x_0$ est le premier élément dans le tableau et $x_{n-1}$ est le dernier élément.

NumPy et Python ainsi que d'autres langages de programmation :

$$
x =
\begin{pmatrix} 
x_{0}  \\
x_{1}  \\
...        \\
x_{n-1} \\
\end{pmatrix}
$$

Notation mathématique typique :

$$
x =
\begin{pmatrix} 
x_{1}  \\
x_{2}  \\
...        \\
x_{n} \\
\end{pmatrix}
$$


## Représentation vectorielle NumPy

En utilisant NumPy, nous sommes capables de créer des vecteurs, qui sont indexables et contiennent des éléments du même type de données (`dtype`). Habituellement, ces vecteurs sont également désignés comme des tableaux unidimensionnels ou 1-D, car ils n'ont qu'une seule dimension indexée, comme expliqué ci-dessus. Un vecteur dans NumPy a les propriétés suivantes :

- Tableau 1-D
- Forme (n,)
- n éléments
- Premier élément indexé [0]
- Dernier élément indexé [n-1]


## Vector Creation


NumPy fournit quelques fonctions utiles pour créer des tableaux remplis de zéros, de uns ou de valeurs aléatoires. Ces tableaux peuvent ensuite être utilisés pour les remplir avec les valeurs désirées. Certaines des fonctions les plus importantes sont présentées ci-dessous. Notez que l'entrée de ces fonctions définit la forme du vecteur généré.


In [3]:
a = np.zeros(4)
print(f"a = np.zeros(4)\na = {a}\na shape = {a.shape}\na data type = {a.dtype}")
print("\n")

a = np.zeros((4,))
print(f"a = np.zeros((4,))\na = {a}\na shape = {a.shape}\na data type = {a.dtype}")
print("\n")

# not a vector, but a matrix of shape 4x4
a = np.ones((4, 4))
print(f"a = np.ones((4, 4))\na = \n{a}\na shape = {a.shape}\na data type = {a.dtype}")
print("\n")

a = np.random.random_sample(5)
print(f"a = np.random.random_sample(5)\na = {a}\na shape = {a.shape}\na data type = {a.dtype}")
print("\n")

a = np.random.rand(4)
print(f"a = np.random.rand(4): \na = {a}, \na shape = {a.shape}, \na data type = {a.dtype}")

a = np.zeros(4)
a = [0. 0. 0. 0.]
a shape = (4,)
a data type = float64


a = np.zeros((4,))
a = [0. 0. 0. 0.]
a shape = (4,)
a data type = float64


a = np.ones((4, 4))
a = 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
a shape = (4, 4)
a data type = float64


a = np.random.random_sample(5)
a = [0.28869465 0.66169719 0.11749079 0.50732435 0.11617478]
a shape = (5,)
a data type = float64


a = np.random.rand(4): 
a = [0.06785305 0.7843115  0.3232037  0.42970331], 
a shape = (4,), 
a data type = float64


### Nous pouvons également créer des séquences :


In [4]:
# we generate float64 values
a = np.arange(4.)
print(f"a = np.arange(4.):     \na = {a}, \na shape = {a.shape}, \na data type = {a.dtype}\n")

# we generate int64 values
a = np.arange(4)
print(f"a = np.arange(4):     \na = {a}, \na shape = {a.shape}, \na data type = {a.dtype}")

a = np.arange(4.):     
a = [0. 1. 2. 3.], 
a shape = (4,), 
a data type = float64

a = np.arange(4):     
a = [0 1 2 3], 
a shape = (4,), 
a data type = int64


### Nous pouvons également créer des vecteurs avec des valeurs personnalisées :


In [5]:
a = np.array([5,7,3,5])
print(f"a = np.array([5,7,3,5])  \na = {a}     \na shape = {a.shape} \na data type = {a.dtype}")
print("\n")

a = np.array([5.,4,3,10])
print(f"a = np.array([5.,4,3,10])\na = {a} \na shape = {a.shape} \na data type = {a.dtype}")

a = np.array([5,7,3,5])  
a = [5 7 3 5]     
a shape = (4,) 
a data type = int64


a = np.array([5.,4,3,10])
a = [ 5.  4.  3. 10.] 
a shape = (4,) 
a data type = float64


Rappelez-vous qu'une forme avec `a.shape = (4,)` indique que le tableau créé est un tableau 1-D.


## Opérations sur les vecteurs

### Indexation des vecteurs
Les éléments des vecteurs peuvent être accédés via l'indexation et le découpage. NumPy fournit un ensemble très riche de possibilités d'indexation et de découpage. Nous ne pouvons couvrir qu'une petite partie de la syntaxe dans ce tutoriel. Si vous souhaitez obtenir une connaissance approfondie, veuillez lire la documentation officielle sur [Slicing and Indexing](https://NumPy.org/doc/stable/reference/arrays.indexing.html). Maintenant, nous voulons clarifier la différence entre *l'indexation* et *le découpage*.

* **L'indexation** signifie faire référence à *un seul élément* d'un tableau par sa position dans le tableau.
* **Le découpage** signifie obtenir un *sous-ensemble* d'éléments d'un tableau en fonction de leurs indices ou de leur plage d'indices.

N'oubliez pas que NumPy commence l'indexation à zéro, donc le 1er élément d'un vecteur $a$ est `a[0]`.
NumPy offre une manière pratique d'accéder au dernier élément d'un tableau sans récupérer $n$ à chaque fois : vous pouvez accéder au dernier élément de $a$ avec `a[-1]`.


In [6]:
a = np.arange(10)
print("a = ", a)

#access a single element
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]} Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

# manipulate a single element in a
a[9] = 100
a[0] = 200
print("a = ", a)

#indexs must be within the range of the vector or NumPy will throw a out of bounds error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

a =  [0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2 Accessing an element returns a scalar
a[-1] = 9
a =  [200   1   2   3   4   5   6   7   8 100]
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


### Découpage de vecteur
Le découpage récupère les éléments d'un tableau en utilisant la syntaxe `début:fin:pas`. Jetons un coup d'œil aux exemples suivants.


In [7]:
a = np.arange(10)
print(f"a        =  {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements with a step size of 2
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements beginning from index 3 to the end
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a        =  [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


### Mathematical Vector Operations

### Opérations sur un seul vecteur
Il existe un certain nombre d'opérations utiles qui impliquent des opérations sur un seul vecteur.


In [8]:
a = np.array([1,2,3,4])
print(f"a             : {a}")

# negate elements of a
b = -a 
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


### Opérations élément par élément entre vecteurs
La plupart des opérations arithmétiques, logiques et de comparaison de NumPy s'appliquent également aux vecteurs. Ces opérateurs fonctionnent sur une base élément par élément. Par exemple 
$$ c_i = a_i + b_i $$


In [9]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element-wise: {a - b}")

Binary operators work element-wise: [2 4 0 0]


Notez que de nombreuses opérations nécessitent les mêmes formes exactes pour leurs deux opérandes.


Bien sûr, pour que cela fonctionne correctement, les vecteurs doivent être de la même taille :


In [10]:
c = np.array([1, 2])
a = np.array([1, 2, 3, 4])

try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


Nous pouvons également combiner des scalaires avec des tableaux :


### Opérations scalaire-vecteur
Les vecteurs peuvent être 'mis à l'échelle' par des valeurs scalaires. Une valeur scalaire est simplement un nombre. Le scalaire multiplie tous les éléments du vecteur.


In [11]:
a = np.array([1, 2, 3, 4])

b = 5 * a 

print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


### Vectorisation : Produit scalaire de vecteurs
Nous voulons tester l'efficacité de la vectorisation en implémentant un produit scalaire de vecteurs entre deux tableaux $a$ et $b$ :

$$
a \cdot b = \sum^{n-1}_{i=0} a_i b_i
$$

Nous allons implémenter la fonction de trois manières :

* **Boucle explicite** : Itérer sur tous les éléments des vecteurs et utiliser l'indexation pour récupérer les éléments, puis effectuer la multiplication et l'addition.
* **Fonction intégrée de NumPy** : Utiliser les fonctions intégrées de NumPy `np.dot`.
* **Vectorisation manuelle de NumPy** : Utiliser la fonction de NumPy pour implémenter une propre version d'une fonction `np.dot` vectorisée.

Le produit scalaire de vecteurs nécessite que les dimensions des deux vecteurs soient les mêmes.


Implémentons notre propre version du produit scalaire ci-dessous :

**En utilisant une boucle for**, implémentez une fonction qui renvoie le produit scalaire de deux vecteurs. La fonction doit retourner, pour les entrées données $a$ et $b$ :
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
Supposez que `a` et `b` ont la même forme.


In [12]:
def dot_vectorized(a, b):
    """
    Compute the dot product of two vectors
    Arguments:
        a: numpy nd array with length n
        b: numpy nd array with length n
    Returns:
        x: dot product of a and b as scalar
    """
    return np.sum(a*b)

In [13]:
def dot_loop(a, b): 
    """
    Compute the dot product of two vectors
    Arguments:
        a: numpy nd array with length n
        b: numpy nd array with length n
    Returns:
        x: dot product of a and b as scalar
    """
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [14]:
a = np.array([5, 3, 2, 1])
b = np.array([-1, 9, 7, 2])
print(f"Function: dot_loop(a, b) \t = {dot_loop(a, b)}")

# Function dot_vectorized
c = dot_vectorized(a, b)
print(f"Function: dot_vectorized(a, b) \t = {dot_loop(a, b)}")

# Build in numpy's dot function
c = np.dot(a, b)
print(f"NumPy Build-In: np.dot(a, b) \t = {c}") 

Function: dot_loop(a, b) 	 = 38
Function: dot_vectorized(a, b) 	 = 38
NumPy Build-In: np.dot(a, b) 	 = 38


Vous pouvez voir que l'implémentation dans `dot_loop()` correspond aux résultats de `dot_vectorized()` et `np.dot()`.


Maintenant, mesurons le **temps** nécessaire à chaque fonction pour calculer deux vecteurs très volumineux.


### Comparaison de vitesse : Vectorisation vs Boucle vs Fonction intégrée
Maintenant, créons deux vecteurs énormes et mesurons le temps nécessaire à chaque approche pour calculer le produit scalaire.


In [15]:
np.random.seed(1337)
a = np.random.rand(10000000) 
b = np.random.rand(10000000)


tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time
print(f"np.dot(a, b) =\t\t\t {c:.4f}")
print(f"Build-In Function: \t\t {1000*(toc-tic):.4f} ms ")
print("\n")



tic = time.time()  # capture start time
c = dot_vectorized(a, b)
toc = time.time()  # capture end time
print(f"dot_vectorized(a, b) =\t\t {c:.4f}")
print(f"Function dot_vectorized(a, b): \t {1000*(toc-tic):.4f} ms ")
print("\n")



tic = time.time()  # capture start time
c = dot_loop(a,b)
toc = time.time()  # capture end time
print(f"dot_loop(a, b) =\t\t {c:.4f}")
print(f"Function dot_loop(a, b): \t {1000*(toc-tic):.4f} ms ")


del(a);del(b)  # remove arrays from memory

np.dot(a, b) =			 2499424.8578
Build-In Function: 		 4.9131 ms 


dot_vectorized(a, b) =		 2499424.8578
Function dot_vectorized(a, b): 	 24.7719 ms 


dot_loop(a, b) =		 2499424.8578
Function dot_loop(a, b): 	 1743.6838 ms 


Comme vous pouvez le constater, l'implémentation vectorisée intégrée offre des performances bien meilleures que la boucle manuelle. Le code vectorisé manuel dans `dot_vectorized` fonctionne également bien, mais un peu plus lentement que la fonction intégrée.

Le code vectorisé s'exécute plus rapidement car il utilise mieux le parallélisme des données disponibles dans le matériel sous-jacent. Les GPU et les CPU modernes mettent en œuvre des pipelines Single Instruction, Multiple Data (SIMD) permettant à plusieurs opérations d'être calculées en parallèle.


In [16]:
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


# Matrices


Les matrices sont des tableaux avec deux dimensions. Encore une fois, les éléments d'une matrice sont tous du même type. Nous utilisons généralement une lettre majuscule par exemple $X$ pour indiquer que cette variable est une matrice. De plus, nous fixons généralement `m` comme le nombre de lignes et `n` comme le nombre de colonnes. Les éléments d'une matrice peuvent être référencés avec un index bidimensionnel. Tout comme pour les vecteurs, nous commençons à l'index 0 lorsque nous programmons avec des matrices.

NumPy et Python ainsi que d'autres langages de programmation avec un index commençant à 0 :
$$
X =
\begin{pmatrix} 
X_{00} & X_{01} & ... & X_{0 (n-1)} \\
X_{10} & X_{11} & ... & X_{1 (n-1)} \\
...    & ...    & ... & ...         \\
X_{(m-1)0} & X_{(m-1)1} & ... & X_{(m-1) (n-1)} \\
\end{pmatrix}
$$


Notation en cours de mathématiques avec un index commençant à $1$ :
$$
X =
\begin{pmatrix} 
X_{11} & X_{12} & ... & X_{1n} \\
X_{21} & X_{22} & ... & X_{1n} \\
...    & ...    & ... & ...    \\
X_{m1} & X_{m2} & ... & X_{mn} \\
\end{pmatrix}
$$


### Création de matrices
Les mêmes fonctions que celles que nous avons utilisées ci-dessus pour créer des vecteurs 1-D créeront également des tableaux 2-D ou n-D.

Remarquez que nous fournissons maintenant un tuple comme forme, par exemple `(1, 5)`. Cela signifie que, pour chaque dimension, nous fournissons le nombre d'indices qui doivent être générés. Pour `(1, 5)`, nous générons uniquement un indice dans la première dimension et pour la deuxième dimension, nous créerons 5 indices.


In [17]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}")
print(f"a = {a}\n")                     


a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}")
print(f"a = \n{a}\n") 


a = np.ones((7, 5))                                                                   
print(f"a shape = {a.shape}")
print(f"a = \n{a}\n") 


a = np.ones((2, 7)) * 7                                                                
print(f"a shape = {a.shape}")
print(f"a = \n{a}\n") 


a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}")
print(f"a = {a}") 

a shape = (1, 5)
a = [[0. 0. 0. 0. 0.]]

a shape = (2, 1)
a = 
[[0.]
 [0.]]

a shape = (7, 5)
a = 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

a shape = (2, 7)
a = 
[[7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]]

a shape = (1, 1)
a = [[0.61731462]]


Vous pouvez également spécifier manuellement les éléments de la matrice. Remarquez que les crochets doivent correspondre à la convention d'impression ci-dessus.


In [18]:
a = np.array([[5], [4], [3]])
print(f"a shape = {a.shape}")
print(f"np.array: a = \n{a} \n")


# You can also continue the next line for better readability
a = np.array([[5],   
              [4],   
              [3]])
print(f"a shape = {a.shape}")
print(f"np.array: a = \n{a}")

a shape = (3, 1)
np.array: a = 
[[5]
 [4]
 [3]] 

a shape = (3, 1)
np.array: a = 
[[5]
 [4]
 [3]]


### Indexing


Les matrices utilisent deux indices, car nous avons deux dimensions. Vous pouvez accéder à un élément de la matrice en utilisant $[i,j] \; \forall 0<i<n-1 \;, 0<j<m-1$. Cela signifie que le premier indice définit la ligne et le deuxième indice définit la colonne $[ligne, colonne]$.


In [19]:
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}")
print(f"a= \n{a}\n")

print("Access an element in the matrix:")
print(f"a[2,0].shape: {a[2, 0].shape}")
print(f"a[2,0] = {a[2, 0]}")
print(f"type(a[2,0]) = {type(a[2, 0])}\nAccessing an element returns a scalar\n")

print("Access a row in the matrix:")
print(f"a[2].shape: {a[2].shape}")
print(f"a[2] = {a[2]}")
print(f"type(a[2]): = {type(a[2])}")

a.shape: (3, 2)
a= 
[[0 1]
 [2 3]
 [4 5]]

Access an element in the matrix:
a[2,0].shape: ()
a[2,0] = 4
type(a[2,0]) = <class 'numpy.int64'>
Accessing an element returns a scalar

Access a row in the matrix:
a[2].shape: (2,)
a[2] = [4 5]
type(a[2]): = <class 'numpy.ndarray'>


Il convient de souligner le dernier exemple. Accéder à une matrice en spécifiant simplement la ligne renverra un *vecteur 1-D*.


### Reshape 

Nous pouvons également [remodeler](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) les tableaux dans une nouvelle forme. Cela signifie que nous pouvons remodeler un tableau 1-D en un tableau 2-D et vice versa.


In [20]:
a = np.arange(6).reshape(-1, 2)
print("a = \n", a)
print("a.shape =",a.shape, "\n")

a = np.arange(6).reshape(3, 2)
print("a = \n", a)
print("a.shape =",a.shape, "\n")

a = np.ones((2, 3)).reshape(-1)
print("a = \n", a)
print("a.shape =",a.shape, "\n")

a = 
 [[0 1]
 [2 3]
 [4 5]]
a.shape = (3, 2) 

a = 
 [[0 1]
 [2 3]
 [4 5]]
a.shape = (3, 2) 

a = 
 [1. 1. 1. 1. 1. 1.]
a.shape = (6,) 



Notez que l'argument -1 indique à cette fonction de déterminer automatiquement le nombre de cette dimension en fonction de la taille du tableau et du nombre des autres dimensions.


### Découpage
Le découpage sur un tableau 2-D crée un nouveau tableau 1-D ou un tableau 2-D en fonction de l'utilisation de `début:fin:pas` appliqué sur chaque dimension.


In [21]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("\na[0, 2:7:1] = ", a[0, 2:7:1])
print("a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array \n")

#access 5 consecutive elements (start:stop:step) in two rows
print("\na[:, 2:7:1] = \n", a[:, 2:7:1])
print("a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array \n")

# access all elements
print("a[:,:] = \n", a[:,:])
print("a[:,:].shape =", a[:,:].shape, "a 2-D array")


# access all elements in one row (very common usage)
print("\na[1,:] = ", a[1,:])
print("a[1,:].shape =", a[1,:].shape, "a 1-D array")

# same as
print("\na[1]   = ", a[1])
print("a[1].shape   =", a[1].shape, "a 1-D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

a[0, 2:7:1] =  [2 3 4 5 6]
a[0, 2:7:1].shape = (5,) a 1-D array 


a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]]
a[:, 2:7:1].shape = (2, 5) a 2-D array 

a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[:,:].shape = (2, 10) a 2-D array

a[1,:] =  [10 11 12 13 14 15 16 17 18 19]
a[1,:].shape = (10,) a 1-D array

a[1]   =  [10 11 12 13 14 15 16 17 18 19]
a[1].shape   = (10,) a 1-D array


# Tâche : Erreur quadratique moyenne
Maintenant, pratiquons vos compétences que vous venez d'apprendre dans ce cahier. Implémentez la moyenne quadratique suivante

$$
L(\vec{a}, \vec{b}) = \frac{1}{n} \sum^{n-1}_{i=0} (a_i - b_i)^2
$$

pour deux vecteurs de deux manières
 
- Implémentation par boucle
- Implémentation vectorisée


In [22]:
def mean_squared_error_loop(a, b):
    """
    Loop implementation of a mean squared error between two vectors
    Arguments:
      a: numpy nd-array with size (n)
      b: numpy nd-array with size (n)
    Returns:
      error: scalar which is the squared error of a and b
    """
    error = 0    
    n = len(a)
    ### START CODE HERE ###
   
    
    ### END CODE HERE ###
    return error

**Conseils**
- Écrivez une boucle en utilisant `range(n)`
- Accédez aux éléments des vecteurs en utilisant `[i]`
- N'oubliez pas de calculer la moyenne


In [23]:
np.random.seed(1337)
a = np.random.randn(1000)
b = np.random.randn(1000)
mean_squared_error_loop(a, b)

0

### Resultat 
1.8469650817618783

In [24]:
def mean_squared_error_vectorized(a, b):
    """
    Vectorized implementation of a mean squared error between two vectors
    Arguments:
      a: numpy nd-array with size (n)
      b: numpy nd-array with size (n)
    Returns:
      error: scalar which is the squared error of a and b
    """
    error = 0    
    ### START CODE HERE ###
   
    
    ### END CODE HERE ###
    return error

**Conseils**
- Utilisez [`np.sum()`](https://numpy.org/doc/stable/reference/generated/numpy.sum.html)
- Vous pouvez utiliser [`np.square()`](https://numpy.org/doc/stable/reference/generated/numpy.square.html) ou `x**2` pour calculer $x^2$
- N'oubliez pas de calculer la moyenne


In [25]:
np.random.seed(1337)
a = np.random.randn(1000)
b = np.random.randn(1000)
mean_squared_error_vectorized(a, b)

0

### Resultat
1.846965081761879

##  Comparison du temp

In [26]:
tic = time.time()
mean_squared_error_loop(a, b)
toc = time.time()
print(f"Loop version duration: {1000*(toc-tic):.4f} ms ")


tic = time.time()
mean_squared_error_vectorized(a, b)
toc = time.time()
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

Loop version duration: 0.0827 ms 
Vectorized version duration: 0.1872 ms 


# Conclusion

- Vous avez appris à créer des tableaux et des matrices Numpy remplis de nombres aléatoires ou de zéros
- Vous avez appris à appliquer des opérations de base aux tableaux Numpy
- Vous avez appris la différence entre le découpage et l'indexation
- Vous avez appris qu'une implémentation vectorisée est souvent beaucoup plus rapide que les solutions basées sur des boucles


# References
```
@Article{         harris2020array,
 title         = {Array programming with {NumPy}},
 author        = {Charles R. Harris and K. Jarrod Millman and St{\'{e}}fan J.
                 van der Walt and Ralf Gommers and Pauli Virtanen and David
                 Cournapeau and Eric Wieser and Julian Taylor and Sebastian
                 Berg and Nathaniel J. Smith and Robert Kern and Matti Picus
                 and Stephan Hoyer and Marten H. van Kerkwijk and Matthew
                 Brett and Allan Haldane and Jaime Fern{\'{a}}ndez del
                 R{\'{i}}o and Mark Wiebe and Pearu Peterson and Pierre
                 G{\'{e}}rard-Marchant and Kevin Sheppard and Tyler Reddy and
                 Warren Weckesser and Hameer Abbasi and Christoph Gohlke and
                 Travis E. Oliphant},
 year          = {2020},
 month         = sep,
 journal       = {Nature},
 volume        = {585},
 number        = {7825},
 pages         = {357--362},
 doi           = {10.1038/s41586-020-2649-2},
 publisher     = {Springer Science and Business Media {LLC}},
 url           = {https://doi.org/10.1038/s41586-020-2649-2}
}
```